#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "0d355b39d275486fa55f89c4c6c3fc82" }
]

[assets]
directory = "./public"
